In [1]:
import numpy as np

In [2]:
# Creating a Tensor

In [10]:
np.array([1, 2, 3, 4]).reshape(4)

array([1, 2, 3, 4])

In [14]:
np.arange(100, 200).size

100

In [18]:
np.arange(100, 200).reshape(2, 2, 5, 5)

array([[[[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]],

        [[125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134],
         [135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144],
         [145, 146, 147, 148, 149]]],


       [[[150, 151, 152, 153, 154],
         [155, 156, 157, 158, 159],
         [160, 161, 162, 163, 164],
         [165, 166, 167, 168, 169],
         [170, 171, 172, 173, 174]],

        [[175, 176, 177, 178, 179],
         [180, 181, 182, 183, 184],
         [185, 186, 187, 188, 189],
         [190, 191, 192, 193, 194],
         [195, 196, 197, 198, 199]]]])

In [16]:
# ones and zeroes

In [42]:
import sys

sys.getsizeof(np.ones((100, 100)).astype("int8")) / (1024 * 1024)

0.0096588134765625

In [48]:
sys.getsizeof(np.ones((20, 20)).astype("int8")) / (1024 * 1024)

0.0005035400390625

In [49]:
# zeroes

In [54]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
# random

In [150]:
(np.random.random((10, 10)) * 100).astype("int")

array([[56, 34, 37, 17, 52, 27, 55, 83, 63, 99],
       [25, 70, 30,  0, 82, 60, 43, 47, 45, 23],
       [12, 12, 13, 28,  2,  5, 42, 36, 66, 88],
       [28, 88, 61, 32,  1, 84, 22, 32, 54, 89],
       [99, 65, 61, 90, 83, 26,  8,  7, 76,  3],
       [24, 83, 85, 11, 33, 26, 10, 45, 57, 29],
       [83, 73, 77, 96,  7, 33, 49, 56, 58, 74],
       [60, 41, 51, 38, 39, 82, 60, 92, 83, 51],
       [65, 14, 68, 58, 72, 61, 11, 27, 31, 80],
       [73, 32, 51, 58, 40, 39, 55, 90, 97, 51]])

In [196]:
# np.random.randint(1, 10, size=(50, 50))

In [197]:
# np.random.randint((1, 10, 8))

In [204]:
np.random.randint(10, 100, size=(10, 3))

array([[33, 94, 52],
       [35, 57, 54],
       [80, 65, 26],
       [89, 80, 71],
       [43, 55, 30],
       [40, 88, 59],
       [81, 44, 35],
       [67, 31, 45],
       [87, 91, 79],
       [12, 65, 89]])

In [209]:
np.ones((2, 2), dtype="int8")

array([[1, 1],
       [1, 1]], dtype=int8)

In [210]:
# Changing the datatypes
# astype -> Type Casting
# dtype -> Casting

In [211]:
# linspace

In [240]:
# To Calculate total values (start +  stop / step)
np.linspace(-100, 100, 20, dtype="float")

array([-100.        ,  -89.47368421,  -78.94736842,  -68.42105263,
        -57.89473684,  -47.36842105,  -36.84210526,  -26.31578947,
        -15.78947368,   -5.26315789,    5.26315789,   15.78947368,
         26.31578947,   36.84210526,   47.36842105,   57.89473684,
         68.42105263,   78.94736842,   89.47368421,  100.        ])

In [241]:
# identity

In [245]:
# Identity Matrix is symetrical and square
# Symetrical -> Upper Trianlge and lower triangle has same values
# Square -> Rows and Columns are same
np.identity(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [260]:
a = np.random.randint(1, 10, size=(3, 4))
np.dot(a, np.random.randint(10, 20, size=(3, 4)).T).astype("int")

array([[271, 347, 349],
       [318, 431, 417],
       [118, 178, 170]])

In [264]:
a = np.random.randint(3, 10, size=(2, 3))

In [266]:
b = np.identity(3)

In [269]:
np.dot(a, b)

array([[7., 9., 3.],
       [4., 8., 6.]])

In [270]:
c = np.random.randint(30, 40, size=(2, 3))

In [278]:
np.dot(a.T, c)

array([[401, 404, 403],
       [607, 628, 621],
       [309, 336, 327]])

In [279]:
# Array Attributes

In [281]:
# ndim
# shape
# size
# dtype
# itemsize

In [288]:
a.itemsize

8