In [1]:
import numpy as np

In [3]:
a = np.arange(100).reshape(10, 10)

In [4]:
# Normal

In [8]:
a[2, 3:5] = [10, 11]

In [11]:
a[3, 2:8] = [20, 21, 22, 23, 24, 25]

In [13]:
# Fancy INdexing

In [21]:
a[[1], [2]]

array([12])

In [24]:
a[[1, 2, 3], [1, 2, 3]]

array([11, 22, 21])

In [27]:
a[[0, 1, 2, 3, 4, 5, 6, 7], [[0, 1, 2, 3, 4, 5, 6, 7]]]

array([[ 0, 11, 22, 21, 44, 55, 66, 77]])

In [30]:
a[[1], :3]

array([[10, 11, 12]])

In [32]:
a[:3, [1]]

array([[ 1],
       [11],
       [21]])

In [35]:
a[[1], 6:9]

array([[16, 17, 18]])

In [37]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 10, 11, 25, 26, 27, 28, 29],
       [30, 31, 20, 21, 22, 23, 24, 25, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
# a[:, [1, 2, 3]]

In [54]:
a[a > 30][a[a > 30] % 2 == 0]

array([38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
       72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [55]:
# Iteration

In [57]:
a = np.arange(100).reshape(10, 10)

In [61]:
# for i in np.nditer(a):
#     print(i)

In [63]:
a = np.arange(100).reshape(5, 5, 2, 2)

In [67]:
# Itearation
# for i in np.nditer(a):
#     print(i)

In [69]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
a = np.arange(200).reshape(5, 5, 2, 2, 2)

In [75]:
a.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [79]:
# Transpose
a.T.T.T

array([[[[[  0,  40,  80, 120, 160],
          [  8,  48,  88, 128, 168],
          [ 16,  56,  96, 136, 176],
          [ 24,  64, 104, 144, 184],
          [ 32,  72, 112, 152, 192]],

         [[  4,  44,  84, 124, 164],
          [ 12,  52,  92, 132, 172],
          [ 20,  60, 100, 140, 180],
          [ 28,  68, 108, 148, 188],
          [ 36,  76, 116, 156, 196]]],


        [[[  2,  42,  82, 122, 162],
          [ 10,  50,  90, 130, 170],
          [ 18,  58,  98, 138, 178],
          [ 26,  66, 106, 146, 186],
          [ 34,  74, 114, 154, 194]],

         [[  6,  46,  86, 126, 166],
          [ 14,  54,  94, 134, 174],
          [ 22,  62, 102, 142, 182],
          [ 30,  70, 110, 150, 190],
          [ 38,  78, 118, 158, 198]]]],



       [[[[  1,  41,  81, 121, 161],
          [  9,  49,  89, 129, 169],
          [ 17,  57,  97, 137, 177],
          [ 25,  65, 105, 145, 185],
          [ 33,  73, 113, 153, 193]],

         [[  5,  45,  85, 125, 165],
          [ 13,  53,  

In [80]:
# Ravel

In [81]:
# Stacking

In [82]:
# Horizontal Stacking
# Vertical Stacking

In [84]:
a = a.ravel()

In [86]:
b = a.copy()

In [90]:
np.hstack((a, b))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
# Vertical Splitting
'A' | 'B' 
# Horizontal Splitting
'A'
---
'B'

In [92]:
a = np.arange(10).reshape(2, 5)

In [93]:
b = np.arange(10, 20).reshape(2, 5)

In [100]:
np.hstack((a, b))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [101]:
np.vstack((a, b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [105]:
# Splitting
# Vertical Splitting
# Horizontal Splitting

In [106]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [109]:
# The End

In [110]:
a = np.arange(100).reshape(2, 2, 5, 5)

In [114]:
# np.vsplit(a, 2)

In [115]:
# a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])