In [7]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
type(a)

list

In [5]:
type(np.array(a))

numpy.ndarray

In [6]:
a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.ndim

1

In [10]:
a.shape

(3,)

In [11]:
a = np.array(2)

In [12]:
a

array(2)

In [13]:
a.ndim

0

In [14]:
a.shape

()

In [ ]:
a = np.array

In [2]:
import time

start = time.time()
a = [x for x in range(100_000_000)]
time.time() - start

4.441187381744385

In [5]:
import sys

sys.getsizeof(a) / (1024 * 1024)

796.4406967163086

In [8]:
import time

start = time.time()
b = np.arange(100_000_000)
time.time() - start

0.22448039054870605

In [9]:
import sys

sys.getsizeof(b) / (1024 * 1024)

762.9395599365234

In [12]:
# np.sin(b)

In [13]:
del a, b

In [23]:
# np.array([[[[1, 2, 3]]]]).shape

In [34]:
np.array(
    [
        [[[1, 2, 3], [3, 4, 5]], [[1, 2, 3], [3, 4, 5]]],
        [[[1, 2, 3], [3, 4, 5]], [[1, 2, 3], [3, 4, 5]]],
    ]
)

array([[[[1, 2, 3],
         [3, 4, 5]],

        [[1, 2, 3],
         [3, 4, 5]]],


       [[[1, 2, 3],
         [3, 4, 5]],

        [[1, 2, 3],
         [3, 4, 5]]]])

In [51]:
np.array(
    [
        [
            [
                [[[1, 2, 3], [3, 4, 5]], [[1, 2, 3], [3, 4, 5]]],
                [[[1, 2, 3], [3, 4, 5]], [[1, 2, 3], [3, 4, 5]]],
                [[[2, 3, 4], [1, 2, 3]], [[3, 4, 5], [4, 5, 5]]],
            ]
        ]
    ]
).shape

(1, 1, 3, 2, 2, 3)

In [68]:
# arange
# np.arange(100).reshape(5, 5, 2, 2)

In [69]:
# create a matrix of even numbers from 1,100

In [81]:
np.arange(2, 101, 2).reshape(2, 25).astype("float")

array([[  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
         46.,  48.,  50.],
       [ 52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,
         74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100.]])

In [ ]:
# pd.read_csv("./home/gaurav/Downloads/trial.csv")
# pd.read_csv("../home/gaurav/Downloads/trial.csv")

In [79]:
np.linspace(10, 20, 6).astype("float")

array([10., 12., 14., 16., 18., 20.])

In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]

In [4]:
a = [x for x in range(100000000)]

In [20]:
b = np.arange(100000000).astype("int8")

In [15]:
import sys

sys.getsizeof(a) / (1024 * 1024)

796.4406967163086

In [19]:
sys.getsizeof(b) / (1024 * 1024)

95.36753845214844

In [21]:
del a, b

In [8]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6]])

In [9]:
a.ndim

2

In [10]:
a.shape

(1, 6)

In [11]:
a.size

6

In [16]:
np.array([[[1, 2, 3, 4, 5, 6], [3, 4, 5, 6, 7, 8]]])

array([[[1, 2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7, 8]]])

In [17]:
# arange

In [23]:
# np.arange(100).reshape(2, 2, 5, 5)

In [4]:
# 2 * np.pi * (np.arange(10, 100, 2).reshape(3, 3, 5))

In [1]:
import numpy as np

In [5]:
# degree to radans

In [28]:
(np.pi / 180) * np.arange(100).reshape(1, 25, 4)

SyntaxError: invalid syntax (4157360474.py, line 1)