In [1]:
# Array Functions

In [3]:
import numpy as np

data = np.arange(200).reshape(50, 4)

In [18]:
data2 = data.copy()

In [19]:
data

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59],
       [ 60,  61,  62,  63],
       [ 64,  65,  66,  67],
       [ 68,  69,  70,  71],
       [ 72,  73,  74,  75],
       [ 76,  77,  78,  79],
       [ 80,  81,  82,  83],
       [ 84,  85,  86,  87],
       [ 88,  89,  90,  91],
       [ 92,  93,  94,  95],
       [ 96,  97,  98,  99],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 1

In [17]:
np.square(data)

array([[    0,     1,     4,     9],
       [   16,    25,    36,    49],
       [   64,    81,   100,   121],
       [  144,   169,   196,   225],
       [  256,   289,   324,   361],
       [  400,   441,   484,   529],
       [  576,   625,   676,   729],
       [  784,   841,   900,   961],
       [ 1024,  1089,  1156,  1225],
       [ 1296,  1369,  1444,  1521],
       [ 1600,  1681,  1764,  1849],
       [ 1936,  2025,  2116,  2209],
       [ 2304,  2401,  2500,  2601],
       [ 2704,  2809,  2916,  3025],
       [ 3136,  3249,  3364,  3481],
       [ 3600,  3721,  3844,  3969],
       [ 4096,  4225,  4356,  4489],
       [ 4624,  4761,  4900,  5041],
       [ 5184,  5329,  5476,  5625],
       [ 5776,  5929,  6084,  6241],
       [ 6400,  6561,  6724,  6889],
       [ 7056,  7225,  7396,  7569],
       [ 7744,  7921,  8100,  8281],
       [ 8464,  8649,  8836,  9025],
       [ 9216,  9409,  9604,  9801],
       [10000, 10201, 10404, 10609],
       [10816, 11025, 11236, 11449],
 

In [24]:
data.T

array([[  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
        104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
        156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196],
       [  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
         53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
        105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
        157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197],
       [  2,   6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,
         54,  58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102,
        106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154,
        158, 162, 166, 170, 174, 178, 182, 186, 190, 194, 198],
       [  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
         55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
     

In [26]:
np.sin(data)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ],
       [-0.90557836, -0.13235175,  0.76255845,  0.95637593],
       [ 0.27090579, -0.66363388, -0.98803162, -0.40403765],
       [ 0.55142668,  0.99991186,  0.52908269, -0.42818267],
       [-0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474],
       [ 0.01770193,  0.85090352,  0.90178835,  0.12357312],
       [-0.76825466, -0.95375265, -0.26237485,  0.67022918],
       [ 0.98662759,  0.39592515, -0.55878905, -0.99975517],
       [-0.521551  ,  0.43616476,  0.99287265,  0.63673801],
       [-0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ],
       [ 0.92002604,  0.

In [27]:
np.tan(data)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00,
        -8.55993401e-01],
       [ 3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00],
       [-2.13489670e+00, -1.33526407e-01,  1.17875355e+00,
        -3.27370380e+00],
       [-2.81429605e-01,  8.87142844e-01, -6.40533120e+00,
        -4.41695568e-01],
       [ 6.61006041e-01, -7.53130148e+01, -6.23498963e-01,
         4.73814720e-01],
       [ 7.75047091e+00, -8.40771255e-01,  3.10309661e-01,
         3.61455441e+00],
       [-1.11721493e+00,  1.60656699e-01,  2.29138799e+00,
        -1.49838734e+00],
       [ 1.77046993e-02,  1.61977519e+00, -2.08661353e+00,
      

In [33]:
# sin2 + cos2
(np.square(np.sin(data)) + np.square(np.cos(data))).astype("float")

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],


In [35]:
np.arange(100, dtype="float")

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [36]:
# Axis

In [ ]:
# Axis -> 0
# Axis -> 1

# Axis in Numpy
axis 0 (Vertical Axis / Row-wise):

    Refers to the first dimension.
    Think of it as operating "down" the rows.
    For example, in a 2D array, axis 0 processes the elements column by column.

axis 1 (Horizontal Axis / Column-wise):

    Refers to the second dimension.
    Think of it as operating "across" the columns.
    For example, in a 2D array, axis 1 processes the elements row by row.

In [41]:
np.arange(100).reshape(20, 5).sum(axis=0)

array([ 950,  970,  990, 1010, 1030])

In [47]:
np.arange(100).reshape(20, 5).sum(axis=1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235, 260, 285, 310,
       335, 360, 385, 410, 435, 460, 485])

In [51]:
np.arange(100).reshape(20, 5).mean(axis=0)

array([47.5, 48.5, 49.5, 50.5, 51.5])

In [63]:
data = np.arange(1, 100).reshape(33, 3)

In [66]:
np.prod(data, axis=1)

array([     6,    120,    504,   1320,   2730,   4896,   7980,  12144,
        17550,  24360,  32736,  42840,  54834,  68880,  85140, 103776,
       124950, 148824, 175560, 205320, 238266, 274560, 314364, 357840,
       405150, 456456, 511920, 571704, 635970, 704880, 778596, 857280,
       941094])

In [69]:
np.prod(data, axis=0)

array([ 8624389262030143488,  2225144297458499584, -2040576755894321152])

In [74]:
np.median(data, axis=1).astype("int")

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [81]:
np.sqrt(np.mean(data, axis=0))

array([7.        , 7.07106781, 7.14142843])

In [82]:
# Round,florr,ceil

In [91]:
np.round(np.sqrt(np.mean(data, axis=0)), 9).astype("int")

array([7, 7, 7])

In [92]:
# Indexing and slicing

In [94]:
data[7, 1]

np.int64(23)

In [97]:
data[13, 1]

np.int64(41)

In [100]:
data[3, -1]

np.int64(12)

In [101]:
data[-1, -1]

np.int64(99)

In [103]:
data[10:, 1:]

array([[32, 33],
       [35, 36],
       [38, 39],
       [41, 42],
       [44, 45],
       [47, 48],
       [50, 51],
       [53, 54],
       [56, 57],
       [59, 60],
       [62, 63],
       [65, 66],
       [68, 69],
       [71, 72],
       [74, 75],
       [77, 78],
       [80, 81],
       [83, 84],
       [86, 87],
       [89, 90],
       [92, 93],
       [95, 96],
       [98, 99]])

In [106]:
data[::2, ::2]

array([[ 1,  3],
       [ 7,  9],
       [13, 15],
       [19, 21],
       [25, 27],
       [31, 33],
       [37, 39],
       [43, 45],
       [49, 51],
       [55, 57],
       [61, 63],
       [67, 69],
       [73, 75],
       [79, 81],
       [85, 87],
       [91, 93],
       [97, 99]])

In [108]:
data[1, 1:]

array([5, 6])

In [110]:
# Normal INdexing

In [114]:
np.arange(100).reshape(2, 2, 25)[1, 1, -8]

np.int64(92)

In [124]:
np.arange(40).reshape(2, 5, 4)[:, ::5, ::4]

array([[[ 0]],

       [[20]]])

In [129]:
np.arange(40).reshape(2, 5, 4)[0, ::2, 1:3]

array([[ 1,  2],
       [ 9, 10],
       [17, 18]])

In [141]:
np.arange(40).reshape(2, 5, 2, 2)[0, -2, -1, -1]

np.int64(15)

In [142]:
# Boolean Indexing

In [148]:
data[data >= 20][data[data >= 20] % 2 == 0]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [155]:
data[(data >= 20) & (data % 2 == 0)]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

In [156]:
# Square all the even numbers from the tesbir gretehert tha 30 but less than 70

In [161]:
np.square((data % 2 == 0 & ((data >= 30) & (data <= 70)))).astype("bool")

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [164]:
# find all the even values greater than 34 and find the mean of the square roots of the square of the values.
data.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46,
        49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94,
        97],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47,
        50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95,
        98],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
        51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96,
        99]])

In [172]:
np.mean(np.sqrt(np.square(data[(data % 2 == 0) & (data > 34)])))

np.float64(67.0)

In [173]:
# Iterating

In [176]:
for i in np.nditer(data):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [179]:
data.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [182]:
data.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [183]:
data.ndim

2

In [185]:
data = np.arange(400).reshape(5, 2, 2, 5, 2, 2)

In [ ]:
# for i in np.nditer(data):
#     print(np.sin(i))

In [194]:
# Creating your own mathematical functions

In [203]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [211]:
class Trignometry:
    def __init__(self, data: np.ndarray):
        self.tensor = data

    def sin_square(self):
        return np.square(np.sin(self.tensor)) + np.square(np.cos(self.tensor))

In [212]:
theta = Trignometry(data)

In [213]:
theta.sin_square()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.

In [199]:
sigmoid(data)

array([[2.        , 1.36787944, 1.13533528, 1.04978707, 1.01831564,
        1.00673795, 1.00247875, 1.00091188, 1.00033546, 1.00012341,
        1.0000454 , 1.0000167 , 1.00000614, 1.00000226, 1.00000083,
        1.00000031, 1.00000011, 1.00000004, 1.00000002, 1.00000001],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1