In [1]:
import numpy as np

In [5]:
a = np.arange(200).reshape(4, 50)

In [18]:
# find all the even nubers from 30 upto 80
a[a % 2 == 0][(a[a % 2 == 0] > 30) & (a[a % 2 == 0] <= 80)]

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80])

In [28]:
a[~(a >= 10)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[~(a % 3 == 0)]

array([  1,   2,   4,   5,   7,   8,  10,  11,  13,  14,  16,  17,  19,
        20,  22,  23,  25,  26,  28,  29,  31,  32,  34,  35,  37,  38,
        40,  41,  43,  44,  46,  47,  49,  50,  52,  53,  55,  56,  58,
        59,  61,  62,  64,  65,  67,  68,  70,  71,  73,  74,  76,  77,
        79,  80,  82,  83,  85,  86,  88,  89,  91,  92,  94,  95,  97,
        98, 100, 101, 103, 104, 106, 107, 109, 110, 112, 113, 115, 116,
       118, 119, 121, 122, 124, 125, 127, 128, 130, 131, 133, 134, 136,
       137, 139, 140, 142, 143, 145, 146, 148, 149, 151, 152, 154, 155,
       157, 158, 160, 161, 163, 164, 166, 167, 169, 170, 172, 173, 175,
       176, 178, 179, 181, 182, 184, 185, 187, 188, 190, 191, 193, 194,
       196, 197, 199])

In [40]:
a[(a % 2 == 0) & (a % 3 == 0)][a[(a % 2 == 0) & (a % 3 == 0)] > 30]

array([ 36,  42,  48,  54,  60,  66,  72,  78,  84,  90,  96, 102, 108,
       114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 186,
       192, 198])

In [42]:
a[(a % 2 == 0) & (a % 3 == 0) & (a > 30)]

array([ 36,  42,  48,  54,  60,  66,  72,  78,  84,  90,  96, 102, 108,
       114, 120, 126, 132, 138, 144, 150, 156, 162, 168, 174, 180, 186,
       192, 198])

In [45]:
# find al the numbers that are greater than 50 and are even

In [48]:
a[(a > 50) & (a % 2 == 0)]

array([ 52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [49]:
# Broadcasting

In [50]:
a = np.arange(10).reshape(5, 2)

In [57]:
b = np.arange(5).reshape(5, 1)

In [58]:
a, b

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0],
        [1],
        [2],
        [3],
        [4]]))

In [69]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
# b


# [0 0
#  1 1
#  2 2
#  3 3
#  4 4
#  5 5]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [82]:
a + b

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [83]:
a = np.arange(10).reshape(5, 2)

In [96]:
b = np.arange(2, 2)

In [97]:
a + b

ValueError: operands could not be broadcast together with shapes (5,2) (0,) 

In [98]:
a = np.arange(20).reshape(5, 4)

In [105]:
b = np.arange(4).reshape(1, 4)

In [108]:
# a + b

In [107]:
# The End

In [115]:
ct = 0
for i in range(100, 300, 2):
    ct += 1
ct

100

In [120]:
ct = 0
for i in range(10, 30, 2):
    for j in range(10, 30, 2):
        ct += 1
    pass
ct

100

In [129]:
ct = 0
i = 1
while i < 20:
    i = i * 2
    ct += 1

In [128]:
ct

5

In [125]:
ct = 0
i = 20  # Start with the maximum value

while i > 1:  # Continue until `i` is greater than 1
    i = i / 2  # Halve `i`
    ct += 1  # Increment count

print(ct)  # Output the count

5
